# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-16.04

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'


steps:
- script: echo "##vso[build.updatebuildnumber]$(v)"
- task: DotNetCoreCLI@2
  displayName: 'Unit Tests'
  continueOnError: false
  inputs:
    command: test
    projects: Bulletin.sln

- task: DotNetCoreCLI@2
  displayName: 'build all'
  inputs:
    projects: Bulletin.sln
    arguments: '-c release /p:Version=$(v)'

- task: CopyFiles@2
  displayName: 'copy generated nugets'
  inputs:
    SourceFolder: src
    Contents: '**/*.nupkg'
    TargetFolder: ' $(build.artifactstagingdirectory)'
    CleanTargetFolder: true
    OverWrite: true
    flattenFolders: true
