# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-16.04

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseGitVersion@5
  displayName: gitversion
  inputs:
    versionSpec: '5.x'
    updateAssemblyInfo: false

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'build'
  inputs:
    projects: Bulletin.sln
    arguments: '--configuration $(BuildConfiguration) /p:Version=$(GitVersion.NuGetVersion)'
    versioningScheme: byBuildNumber

- task: CopyFiles@2
  displayName: 'copy generated nuget packages'
  inputs:
    SourceFolder: src
    Contents: '**/*.nupkg'
    TargetFolder: ' $(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    OverWrite: true
    flattenFolders: true

- task: DotNetCoreCLI@2
  displayName: 'Unit Tests'
  continueOnError: false
  inputs:
    command: test
    projects: Bulletin.sln
    arguments: --collect:"XPlat Code Coverage"

- task: NuGetCommand@2
  displayName: publish
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'Bulletin Nuget'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
